export const tableData = [
    {
      id: 1,
      name: "John",
      age: 28,
      gender: "Male",
      checkbox: false,
      rating: 4.5,
      editable: false,
    },
    {
      id: 2,
      name: "Alice",
      age: 24,
      gender: "Female",
      checkbox: false,
      rating: 4.2,
      editable: false,
    },
    {
      id: 3,
      name: "Bob",
      age: 30,
      gender: "Male",
      checkbox: false,
      rating: 4.1,
      editable: false,
    },
    {
      id: 4,
      name: "Charlie",
      age: 27,
      gender: "Male",
      checkbox: false,
      rating: 4.3,
      editable: false,
    },
    {
      id: 5,
      name: "Diana",
      age: 32,
      gender: "Female",
      checkbox: false,
      rating: 4.6,
      editable: false,
    },
    {
      id: 6,
      name: "Edward",
      age: 29,
      gender: "Male",
      checkbox: false,
      rating: 4.0,
      editable: false,
    },
    {
      id: 7,
      name: "Fiona",
      age: 25,
      gender: "Female",
      checkbox: false,
      rating: 4.5,
      editable: false,
    },
    {
      id: 8,
      name: "George",
      age: 31,
      gender: "Male",
      checkbox: false,
      rating: 4.2,
      editable: false,
    },
    {
      id: 9,
      name: "Hannah",
      age: 26,
      gender: "Female",
      checkbox: false,
      rating: 4.3,
      editable: false,
    },
    {
      id: 10,
      name: "Ian",
      age: 28,
      gender: "Male",
      checkbox: false,
      rating: 4.4,
      editable: false,
    },
    {
      id: 11,
      name: "Jessica",
      age: 24,
      gender: "Female",
      checkbox: false,
      rating: 4.6,
      editable: false,
    },
    {
      id: 12,
      name: "Kevin",
      age: 33,
      gender: "Male",
      checkbox: false,
      rating: 4.1,
      editable: false,
    },
    {
      id: 13,
      name: "Laura",
      age: 27,
      gender: "Female",
      checkbox: false,
      rating: 4.2,
      editable: false,
    },
    {
      id: 14,
      name: "Michael",
      age: 30,
      gender: "Male",
      checkbox: false,
      rating: 4.3,
      editable: false,
    },
    {
      id: 15,
      name: "Nina",
      age: 28,
      gender: "Female",
      checkbox: false,
      rating: 4.4,
      editable: false,
    },
    {
      id: 16,
      name: "Oscar",
      age: 26,
      gender: "Male",
      checkbox: false,
      rating: 4.5,
      editable: false,
    },
    {
      id: 17,
      name: "Paula",
      age: 29,
      gender: "Female",
      checkbox: false,
      rating: 4.1,
      editable: false,
    },
    {
      id: 18,
      name: "Quincy",
      age: 25,
      gender: "Male",
      checkbox: false,
      rating: 4.3,
      editable: false,
    },
    {
      id: 19,
      name: "Rachel",
      age: 32,
      gender: "Female",
      checkbox: false,
      rating: 4.2,
      editable: false,
    },
    {
      id: 20,
      name: "Steve",
      age: 27,
      gender: "Male",
      checkbox: false,
      rating: 4.4,
      editable: false,
    },
    {
      id: 21,
      name: "Tina",
      age: 31,
      gender: "Female",
      checkbox: false,
      rating: 4.5,
      editable: false,
    },
  ];